name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      IMG_URL:
        description: 'Link to boot or recovery image (.img or .img.lz4)'
        required: true
        default: ''

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - name: Check Out repository
      uses: actions/checkout@v4

    - name: Prepare the environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y python3 python3-pip cpio wget zip aria2 lz4 file git bash
        pip install --upgrade pip
        pip install twrpdtgen
        mkdir -p dt img

    - name: Download boot/recovery image
      run: |
        echo "Downloading image from: ${{ github.event.inputs.IMG_URL }}"
        cd img
        aria2c -x 16 -s 16 "${{ github.event.inputs.IMG_URL }}"
        ls -lh

    - name: Decompress .lz4 if needed
      run: |
        cd img
        IMG_FILE=$(ls)
        if file "$IMG_FILE" | grep -q "LZ4 compressed"; then
          echo "Detected LZ4 image, decompressing..."
          lz4 -d "$IMG_FILE" "${IMG_FILE%.lz4}"
          rm "$IMG_FILE"
        fi
        ls -lh
        cd ..

    - name: Generate TWRP device tree
      run: |
        IMG_PATH=$(find img -type f -name "*.img" | head -n 1)
        echo "Using image: $IMG_PATH"
        if [ -z "$IMG_PATH" ]; then
          echo "❌ No valid .img found, aborting."
          exit 1
        fi
        python3 -m twrpdtgen -o dt/ "$IMG_PATH"

    - name: Create device tree ZIP
      run: |
        cd dt
        zip -r ../DeviceTree.zip .
        cd ..

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: DeviceTree.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: Generated TWRP device tree
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
